name: Setup project
description: Specific steps to checkout the project and setup the environment
runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        overwrite-settings: false # This will use our runner settings.xml for Maven

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
